version: "3"
volumes:
  data:
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5.8
    ports:
    - "3306:3306"
    volumes:
    - data:/var/lib/mysql
    env_file:
    - docker.env
